### PR TITLE
Remove from path

### PR DESCRIPTION
**Pull request by perrin4869**
Here is another implementation for your consideration :)
Much cleaner I think

### CODE REVIEW

**Comment by jamuhl** [comment]
- can you extract https://github.com/i18next/i18next-express-middleware/pull/6/files#diff-1fdf421c05c1140f6d71444ea2b27638R22 to a own function in utils `if(detector === 'path' && options.removeLngFromUrl) utils.removeLngFromUrl(req, i18next.services.languageDetector.options.lookupFromPathIndex);`

- instead of returning array [lng, detector] could you just return lng from languageDetector.detect and append detector to req.i18nextLookupName = 'path'

**Comment by jamuhl** [comment]
like this one a lot more....thanks

**Comment by perrin4869** [comment]
This is slightly more functional. I think returning multiple variables from `languageDetector.detect` is also slightly more functional

**Comment by jamuhl** [comment]
You're right...more functional...but returning just lng is more in line with the API of other language detectors. Will merge and publish updated version.

**Comment by jamuhl** [comment]
v0.1.0

**Comment by perrin4869** [comment]
Thanks man!

**Comment by jamuhl** [comment]
thank you for your contribution...help is very welcome

**Comment by perrin4869** [comment]
dude you have the best i18n framework out there. It's true that it feels awesome to help other people but the truth is everyone is busy. Open source projects like this rely on selfish people like me to grow, and that's why your framework is the best out there :D

**Comment by perrin4869** [comment]
but yeah this solution is much better than the one I made at first, so it's great you rejected my previous pull request, only with a great maintainer can this be as good as it is

**Pull request merged**
