### PR TITLE
fix: allow to pass secure to cookie options

### PR DESCRIPTION
**Pull request by fastman**
HI,
This one adds option to enable/disable `secure` param set for a cookie. 
Let me know what do you think about this change.

### CODE REVIEW

**Comment by jamuhl** [comment]
thank you for contributing. was published on npm in i18next-express-middleware@1.3.0

**Comment by fastman** [comment]
okay, I think I should update this MR with the check if the `cookieSecure` option is present and set this param only if this option is present in order to preserve the default behaviour where `Cookie` module checks if the connection is secure

**Comment by jamuhl** [comment]
feel free to add another PR with the change...will publish an update

**Comment by fastman** [comment]
Thank you, done!

**Pull request merged**
