### PR TITLE
fixes cookie name lookup

### PR DESCRIPTION
**Pull request by youbs**
Hi,

Tank you for your work!

I have a lot of issues with the beta, I can't make it work with express (the detected language is always undefined)

Here is a first fix for an issue I found in the code, it does not fix my undefined language, but it's a first step :)

### CODE REVIEW

**Comment by jamuhl** [comment]
you added the language detector like: https://github.com/i18next/i18next-express-middleware#language-detection ?

**Comment by jamuhl** [comment]
fixed in 0.0.16

**Comment by youbs** [comment]
Here is my setup:

Express config:
```
var
    i18next        = require('./i18next'),
    i18nextMw      = require('i18next-express-middleware')
;
  // ...
  // Register i18next
  app.use(i18nextMw.handle(i18next));
```

i18next.js:
```
'use strict';

var i18next    = require('i18next'),
    middleware = require('i18next-express-middleware'),
    Backend    = require('i18next-node-fs-backend'),
    path       = require('path')
;

var loadPath = path.join(path.resolve(__dirname), '/locales/{{ns}}.{{lng}}.json');

var options = {
    whitelist: ['en', 'fr'],
    fallbackLng: 'en',
    ns: 'app',
    defaultNS: 'app',
    fallbackNS: 'app',
    saveMissing: false,
    debug: true,
    backend : {
        loadPath: loadPath
    },
    detection: {
        order: ['querystring', 'cookie', 'header'],
        lookupQuerystring: 'lang',
        lookupCookie: 'lang',
        lookupSession: 'lang',
        caches: ['cookie']
    }
};

i18next
    .use(middleware.LanguageDetector)
    .use(Backend)
    .init(options);

module.exports = i18next;
```

I just tried your patch, still no success (I have a link with `?lang=fr` on my homepage)
I still have `i18next::codeUtils: rejecting non-whitelisted language code: undefined` logged for each translated string, so everything fallback to `en`
Do you see something that could help?

Thanks for your time,

**Comment by jamuhl** [comment]
where do you access the `t` function?

inside request `req.t('someKey')` or directly from `require('./i18next').t`?

the second would not work - as i18next gets setup to work inside a request. The language would have to be set manual if using i18next directly outside of request.

**Comment by youbs** [comment]
I ha

**Comment by jamuhl** [comment]
to easier debug you can:

```
var i18next    = require('i18next/lib'),
    middleware = require('i18next-express-middleware/lib'),
    Backend    = require('i18next-node-fs-backend/lib'),
```

in node_modules/i18next-express-middleware https://github.com/i18next/i18next-express-middleware/blob/master/lib/index.js#L39 logout the language to see if it detects.

**Comment by jamuhl** [comment]
hm...never used handlebars on serverside. but you need somehow set that for the current request.

http://stackoverflow.com/questions/17274142/setting-a-handlebars-helper-to-return-a-specific-value-per-request-in-express might help.

basically it's more an issue with handlebars singleton breaking when running in production.

**Comment by youbs** [comment]
Thank you I just managed to make it work with your help,

So I registered this helper just after `app.use(i18nextMw.handle(i18next));`:

```
  // Register "t" function
  app.use(function(req, res, next) {
    Handlebars.registerHelper('t', function(options) {
      return req.t;
    });
    next();
  });
```

Thanks again man, sorry for your time,
I imagine this could be a part of a plugin, I'll see what I can do,

Have a nice day,

**Comment by jamuhl** [comment]
another option would be to pass the language to your helper, like 

http://stackoverflow.com/questions/25611501/how-to-get-access-to-request-object-from-custom-handlebars-helper

`<div>{{t key ../req.lng }}</div>`

```
helpers.t = function(key, lng) {
  var result;
  try {
    result = i18next.t(key, {lng: lng});
  } catch(err) {
    return '*** missing ***';
  }

  return new handlebars.SafeString(result);
};
```

**Comment by jamuhl** [comment]
great you got a working solution...yes i hope people come up with new helpers, plugins,...so we could add them for others here http://i18next.github.io/i18next.com/docs/ecosystem/

**Comment by adyz** [comment]
Hi @youbs -- did you had any concurrency issues? For me, sometimes I get the wrong language when concurrent requests happen. Any thoughts?

**Pull request closed without merging**
